server:
  port: 8080
  allowed_origins:
    - "http://localhost:5175"
    - "https://www.shopshredder.de"
    - "http://localhost:8000"
    - "http://localhost:80"
  app_url: "http://localhost"

sandbox:
  url_prefix: "sandbox-"
  url_suffix: ".shopshredder.de"
  default_lifetime: 60

auth:
  username: "admin"
  password: "password"

guard:
  max_total_sandboxes: 32
  max_sandboxes_per_ip: 2
  max_sandbox_lifetime: 60

#database:
#  host: "database"
#  port: 5432
#  user: "mrpix_sandbox"
#  password: "sandXbox_mrpix2025"
#  name: "mrpix_sandbox"

#sentry:
#  dsn: "https://b578c482893c9c27e211e738deca9889@sentry.mr-pixel.de/15"