version: '3.8'

services:
  proxy:
    image: "traefik:v2.10"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/traefik:/etc/traefik
    networks:
      - sandbox-network
      - internal

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - GOPROXY=proxy.golang.org
      - DOCKER_HOST=unix:///Users/manuel.kienlein/.docker/run/docker.sock #unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/Users/manuel.kienlein/.docker/run/docker.sock #/var/run/docker.sock
      - ./config.yml:/app/config.yml
    networks:
      - sandbox-network
      - internal
    depends_on:
      database:
        condition: service_healthy

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:8080
    expose:
      - 80
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    networks:
      - sandbox-network
    depends_on:
      backend:
        condition: service_healthy

  database:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    volumes:
        - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mrpix_sandbox
      POSTGRES_PASSWORD: sandXbox_mrpix2025
      POSTGRES_DB: mrpix_sandbox
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U mrpix_sandbox -d mrpix_sandbox'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  sandbox-network:
    driver: bridge
  internal:
    name: internal
    driver: bridge

volumes:
  database_data:
    driver: local