version: '3.8'

services:
  backend:
    image: ghcr.io/mr-pixel-kg/mpxsandbox-backend:latest
    restart: always
    expose:
      - 8080
    environment:
      - GOPROXY=proxy.golang.org
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RUN_MIGRATIONS_ON_START=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mpxsandbox/config.yml:/app/config.yml
    networks:
      - sandbox-network
      - internal
    depends_on:
      database:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.sandbox-backend.entrypoints=websecure"
      - "traefik.http.routers.sandbox-backend.rule=Host(`sandbox-api.zion.mr-pixel.de`)"
      - "traefik.http.routers.sandbox-backend.tls=true"
      - "traefik.http.routers.sandbox-backend.tls.certresolver=production"

  frontend:
    image: ghcr.io/mr-pixel-kg/mpxsandbox-frontend:latest
    restart: always
    expose:
      - 80
    environment:
      - VITE_BACKEND_URL=https://sandbox-api.zion.mr-pixel.de
    networks:
      - sandbox-network
      - internal
    depends_on:
      backend:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.sandbox-frontend.entrypoints=websecure"
      - "traefik.http.routers.sandbox-frontend.rule=Host(`sandbox.zion.mr-pixel.de`)"
      - "traefik.http.routers.sandbox-frontend.tls=true"
      - "traefik.http.routers.sandbox-frontend.tls.certresolver=production"

  database:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mrpix_sandbox
      POSTGRES_PASSWORD: sandXbox_mrpix2025
      POSTGRES_DB: mrpix_sandbox
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U mrpix_sandbox -d mrpix_sandbox'"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 80s

networks:
  sandbox-network:
    driver: bridge
  internal:
    external:
      name: internal

volumes:
  database_data:
    driver: local
