basePath: /
definitions:
  images.ImageDeleteResponse:
    properties:
      message:
        example: Docker Image removed successfully
        type: string
      status:
        example: success
        type: string
    type: object
  images.PullImageRequest:
    properties:
      image_name:
        example: dockware/dev
        type: string
      image_tag:
        example: 6.6.8.2
        type: string
    type: object
  images.PullImageResponse:
    properties:
      message:
        example: Docker Image created successfully
        type: string
      status:
        example: success
        type: string
    type: object
  sandboxes.SandboxCreateRequest:
    properties:
      image_name:
        example: dockware/dev:6.6.8.2
        type: string
      lifetime:
        example: 1440
        type: integer
    type: object
  sandboxes.SandboxCreateResponse:
    properties:
      container_id:
        example: 9a7f95b73018432cb88ebed68046c59a4bed05b2abc809f6fbf39a1173c06ac9
        type: string
      container_name:
        example: sandbox-67777b4e-946f-4462-b689-3c608d2d7938
        type: string
      created_at:
        example: "2021-09-01T12:00:00Z"
        type: string
      destroy_at:
        example: "2021-09-01T12:00:00Z"
        type: string
      image:
        example: dockware/dev:6.6.8.2
        type: string
      message:
        example: Sandbox created successfully
        type: string
      sandbox_id:
        example: 67777b4e-946f-4462-b689-3c608d2d7938
        type: string
      status:
        example: success
        type: string
      url:
        example: https://sandbox-67777b4e-946f-4462-b689-3c608d2d7938.shopshredder.zion.mr-pixel.de
        type: string
    type: object
  sandboxes.SandboxDeleteResponse:
    properties:
      message:
        example: Docker Image removed successfully
        type: string
      status:
        example: success
        type: string
    type: object
  services.Image:
    properties:
      created_at:
        example: "2013-08-20T18:52:09.000Z"
        type: string
      id:
        example: a407dee395ed97ead1e40c7537395d6271c07cc89c317f8eda1c19f6fc783695
        type: string
      image_name:
        example: dockware/dev
        type: string
      image_tag:
        example: 6.6.8.2
        type: string
      size:
        example: 1048576
        type: integer
    type: object
  services.SandboxInfo:
    properties:
      container_id:
        type: string
      container_name:
        type: string
      created_at:
        type: string
      destroy_at:
        type: string
      id:
        type: string
      image:
        type: string
      state:
        type: string
      status:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Management API for Docker Sandbox Environment
  license:
    name: MIT
  title: mpXsandbox API
  version: 1.0.0
paths:
  /api/auditlog:
    get:
      consumes:
      - '*/*'
      description: Get the last 300 audit log entries.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BasicAuth: []
      summary: Endpoint to the last 300 audit log entries.
      tags:
      - System Management
  /api/auth:
    get:
      consumes:
      - '*/*'
      description: Test the authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Endpoint to test the authentication.
      tags:
      - System Management
  /api/health:
    get:
      consumes:
      - '*/*'
      description: Get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - System Management
  /api/images:
    get:
      consumes:
      - application/json
      description: Get a list of docker image
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.Image'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List of Docker Image
      tags:
      - Docker Image Management
    post:
      consumes:
      - application/json
      description: Pulls a docker image and register it into the system
      parameters:
      - description: Image Input
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/images.PullImageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/images.PullImageResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Pull Docker Image
      tags:
      - Docker Image Management
  /api/images/{id}:
    delete:
      consumes:
      - application/json
      description: Removes a docker image form the system
      parameters:
      - description: Image ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/images.ImageDeleteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Remove Docker Image
      tags:
      - Docker Image Management
    get:
      consumes:
      - application/json
      description: Get details about a docker image
      parameters:
      - description: Image ID
        example: a407dee395ed97ead1e40c7537395d6271c07cc89c317f8eda1c19f6fc783695
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Image'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Details about a Docker Image
      tags:
      - Docker Image Management
  /api/sandboxes:
    get:
      consumes:
      - application/json
      description: List sandbox environments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.SandboxInfo'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: List sandbox environments
      tags:
      - Sandbox Management
    post:
      consumes:
      - application/json
      description: Creates a new sandbox docker container
      parameters:
      - description: Image Input
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/sandboxes.SandboxCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sandboxes.SandboxCreateResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Create new sandbox
      tags:
      - Sandbox Management
  /api/sandboxes/{id}:
    delete:
      consumes:
      - application/json
      description: Removes a sandbox docker container
      parameters:
      - description: Sandbox ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sandboxes.SandboxDeleteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Remove Sandbox Environment
      tags:
      - Sandbox Management
    get:
      consumes:
      - application/json
      description: Get details about a sandbox environment
      parameters:
      - description: Sandbox ID
        example: 67777b4e-946f-4462-b689-3c608d2d7938
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.SandboxInfo'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Details about a Sandbox
      tags:
      - Sandbox Management
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
